name: CI to Docker Hub

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: your_username
  DOCKERHUB_PASSWORD: your_password  

jobs:
  
  order_service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build and push Order Service Docker image
      run: |
        cd order
        mvn clean package -DskipTests
        docker build . -t ${{ env.DOCKERHUB_USERNAME }}/order:latest
        docker push ${{ env.DOCKERHUB_USERNAME }}/order:latest


  delivery_service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and push Delivery Service Docker image
      run: |
        cd delivery
        mvn clean package -DskipTests
        docker build . -t ${{ env.DOCKERHUB_USERNAME }}/delivery:latest
        docker push ${{ env.DOCKERHUB_USERNAME }}/delivery:latest


  store_service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and push Store Service Docker image
      run: |
        cd store
        mvn clean package -DskipTests
        docker build . -t ${{ env.DOCKERHUB_USERNAME }}/store:latest
        docker push ${{ env.DOCKERHUB_USERNAME }}/store:latest